### ISSUE TITLE
Cloned VMs in VMware  have all the same uuid

### ISSUE THREAD

**Issue by GER-Space** [trento-project/agent#223]
the UUID is not dynamically generated at the first startup of the agents.  --> All agents on cloned VMs under vmware share the same uuid and mess up trento

setting the undocumented `force-agent-id: <some-new-id>` in **/etc/trento/agent.yaml** can solve the problem, but either it needs to be documented or a workaround needs to be found.

**Comment by stefanotorresi** [comment]
@GER-Space thanks for pointing out your use case.

The flag you're mentioning is in fact documented in the readme but it already states that it should not be used in production environments, where relying on automatic generation of the system identifier by systemd is way safer.

We rely on `/etc/machine-id` to be unique to generate the Trento Agent UUID so, as you're cloning VMs, you need to ensure you're not violating a fundamental assumption Trento and other system tools might rely upon, which is that that file contains an actually unique host identifier.
You can refer to upstream systemd documentation for further insights on how to achieve this: https://www.freedesktop.org/software/systemd/man/machine-id.html

**Comment by stefanotorresi** [comment]
We'll consider adding a pre-flight check to prevent registration from happening in the first place in the case we find and existing agent id.
